name: Docker Compose Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:   # Enable manual execution
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout cÃ³digo fuente
      uses: actions/checkout@v2

    - name: Configurar Docker Buildx
      uses: docker/setup-buildx-action@v1


    - name: Construir y publicar imagen Docker
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker-compose -f workflows/docker-compose.yml build
        docker-compose -f workflows/docker-compose.yml push

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Setup known_hosts
      run: |
       ssh-keyscan $(hostname -I | awk '{print $1}') >> ~/.ssh/known_hosts

    - name: Update docker-compose
      run: |
       ssh alvaro@172.23.121.25 "cd /mnt/c/Users/alvar/Desktop/Coding/JKU/cloud_computing/WS23_CloudComputing/workflows && sudo docker-compose pull && sudo docker-compose up -d"

